apiVersion: v1
kind: Service
metadata:
  name: fastapi
spec:
  selector:
    app: {{ .Release.Name }}-fastapi
  type: {{ .Values.service.type }} 
  ports:
  - name: fastapi
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}